{
 "title": "Forums",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Forum and Subforum Posts Distribution",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT f.title AS forum_title, s.title AS subforum_title, s.posts_count\r\nFROM forums f\r\nJOIN subforums s ON f.forum_id = s.forum_id\r\nWHERE NOT EXISTS (\r\n    SELECT 1 \r\n    FROM forums AS t2 \r\n    WHERE t2.crawling_date > f.crawling_date\r\n)\r\nORDER BY s.posts_count DESC;\r\n"
    }
   ]
  },
  {
   "title": "Forum Activity Comparison",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n    t1.title,\r\n    t1.topics_count,\r\n    t1.posts_count\r\nFROM forums as t1\r\nWHERE NOT EXISTS (\r\n    SELECT 1 \r\n    FROM forums AS t2 \r\n    WHERE t2.crawling_date > t1.crawling_date\r\n)\r\nGROUP BY\r\n    t1.title,\r\n    t1.topics_count,\r\n    t1.posts_count;\r\n"
    }
   ]
  },
  {
   "title": "Top Forum Contributors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT t1.last_post_author, SUM(posts_count) AS total_posts\r\nFROM forums as t1\r\nWHERE NOT EXISTS (\r\n    SELECT 1 \r\n    FROM forums AS t2 \r\n    WHERE t2.crawling_date > t1.crawling_date\r\n)\r\nGROUP BY t1.last_post_author\r\nORDER BY total_posts DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Activity in subforum \"Biete\"",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "germania",
     "rawSql": "SELECT t1.title, t1.posts_count, t1.topics_count\r\nFROM subforums AS t1\r\nINNER JOIN forums f ON t1.forum_id = f.forum_id AND f.title = 'Biete'\r\nWHERE NOT EXISTS (\r\n  SELECT 1\r\n  FROM subforums AS t2\r\n  WHERE t2.crawling_date > t1.crawling_date\r\n)"
    }
   ]
  },
  {
   "title": "Activity in subforum \"Suche\"",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dataset": "germania",
     "rawSql": "SELECT t1.title, t1.posts_count, t1.topics_count\r\nFROM subforums AS t1\r\nINNER JOIN forums f ON t1.forum_id = f.forum_id AND f.title = 'Suche'\r\nWHERE NOT EXISTS (\r\n  SELECT 1\r\n  FROM subforums AS t2\r\n  WHERE t2.crawling_date > t1.crawling_date\r\n)"
    }
   ]
  },
  {
   "title": "Number of posts per subforum over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.subforums WHERE title = 'Drogen & Medikamente' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.subforums WHERE title = 'Waren' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.subforums WHERE title = 'Services' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.subforums WHERE title = 'Sonstiges' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of posts per forum over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Information' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Feedback & Kritik' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Vorstellungen' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Szene News' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'COVID-19' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Überleben in Krisen- und Katastrophenfällen' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Biete' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Suche' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'VENDOR' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Pygmalions Refugium' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, posts_count FROM germania.forums WHERE title = 'Talk' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of topcis per forum over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Information' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Feedback & Kritik' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Vorstellungen' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Szene News' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'COVID-19' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Überleben in Krisen- und Katastrophenfällen' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Biete' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Suche' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'VENDOR' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Pygmalions Refugium' LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT crawling_date, title, topics_count FROM germania.forums WHERE title = 'Talk' LIMIT 50 "
    }
   ]
  }
 ]
}