{
 "title": "Users General",
 "time": { "from": "2022-11-06T00:00:00.000Z", "to": "2023-09-05T00:00:00.000Z" },
 "panels": [
  {
   "title": "Registration rate over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT registration_date, COUNT(*) as count\r\nFROM users_general AS t1\r\nWHERE NOT EXISTS (\r\n  SELECT 1\r\n  FROM users_general AS t2\r\n  WHERE t2.crawled_datetime > t1.crawled_datetime\r\n)\r\nGROUP BY registration_date;"
    }
   ]
  },
  {
   "title": "Latest User Title Distribution",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT title, COUNT(*) as count \r\nFROM users_general AS t1 \r\nWHERE NOT EXISTS \r\n(SELECT 1 \r\nFROM users_general AS t2 \r\n    WHERE t2.crawled_datetime > t1.crawled_datetime\r\n) GROUP BY title;"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 14 },
   "targets": [
    {
     "dataset": "germania",
     "rawSql": "SELECT name, number_of_posts, points\r\nFROM users_general AS t1\r\nWHERE NOT EXISTS (\r\n  SELECT 1\r\n  FROM users_general AS t2\r\n  WHERE t2.crawled_datetime > t1.crawled_datetime\r\n)\r\nGROUP BY name, number_of_posts, points\r\nORDER BY number_of_posts DESC;"
    }
   ]
  },
  {
   "title": "Number of posts per Registration Date",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT number_of_posts, registration_date\r\nFROM users_general AS t1\r\nWHERE NOT EXISTS (\r\n  SELECT 1\r\n  FROM users_general AS t2\r\n  WHERE t2.crawled_datetime > t1.crawled_datetime\r\n)\r\nORDER BY number_of_posts;"
    }
   ]
  },
  {
   "title": "User Title Distribution over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Mitglied' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Elite' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Vendor' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Moderator' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Administrator' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Pygmalion Syndikat' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Observer' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Gesperrt' GROUP BY crawled_datetime LIMIT 50 "
    },
    {
     "dataset": "germania",
     "rawSql": "SELECT title, COUNT(*), crawled_datetime FROM germania.users_general WHERE title = 'Banned' GROUP BY crawled_datetime LIMIT 50 "
    }
   ]
  },
  {
   "title": "User Engagement over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT time_sec, SUM(total_posts) as total_posts, SUM(total_points) as total_points\r\nFROM (\r\n    SELECT UNIX_TIMESTAMP(crawled_datetime) as time_sec, SUM(number_of_posts) as total_posts, SUM(points) as total_points\r\n    FROM germania.users_general\r\n    GROUP BY time_sec\r\n) AS aggregated_data\r\nGROUP BY time_sec\r\n"
    }
   ]
  }
 ]
}